### ISSUE TITLE
Release testing checklist for RiTa2

### ISSUE THREAD

**Issue by dhowe** [dhowe/rita4j#37]
should include java/js/node/android/browser, etc (adapt from the existing version)

**Comment by cqx931** [comment]
#### How do I test a new release?
- [ ] Step carefully through all 'quickstart' installation [instructions]
(http://rednoise.org/rita/quickstart.php)
- [ ] Go through [Android README file] - TODO

**Before release**
- Run each of the RiTa [examples](http://rednoise.org/rita/examples.php) on each of the platforms:

_JS_
- [ ] In the browser with dom (Chrome/Firefox)
- [ ] In the browser with p5.js
- [ ] Test 'Analysis' and 'RandomRhymes' examples with no lexicon, using rita-web-nolex.js, rather than rita-web.js and verify that the correct warning message is shown
 
_Java_
- [ ] In Processing
- [ ] In Processing for Android (Ignore the example: ReplaceableWriting for Android tests)
- [ ] As a standalone Java program (jar)
- [ ] As a standalone Android app (jar)

**Post release**  
Pay attention to any error or warning message during the process:
- [ ] Install RiTa via `npm install` and test instructions on npm [README page](https://www.npmjs.com/package/rita#in-nodejs)
- [ ] Test the npm/runkit example here: https://runkit.com/npm/rita 
- [ ] Download from the library tool within the Processing IDE
- [ ] Check that processing library tool is prompting for update if older rita exists
- [ ] Test RiTa In the browser via [browserify instructions] - TODO
- [ ] Verify the existence and version # of the [RiTa lib on cdnjs](https://cdnjs.com/libraries/rita/)
- [ ] Verify the existence and version # of the [rita.txt file on rednoise](http://rednoise.org/rita/rita.txt)
  &nbsp; 

_Testing [RiTa website](http://rednoise.org/rita/)_ 

- [ ] Check and fix errors in the console tab of developer tools for each page 
- [ ] Check links (with a [link-checker](https://www.deadlinkchecker.com/website-dead-link-checker.asp)) and fix any errors  
- [ ] Check the UI of the website with desktop and mobile devices
- [ ] Verify the version # on [RiTa downloads page](http://rednoise.org/rita/download.php)
- [ ] Verify download page(http://rednoise.org/rita/download.php) - TODO: more details are to be added
- [ ] Verify that both download links work: [rita.zip](http://rednoise.org/rita/rita.zip) and [RiTa.zip](http://rednoise.org/rita/rita.zip)

**Comment by cqx931** [comment]
Need to update some of the example cases on https://github.com/dhowe/RiTaJS

**Comment by dhowe** [comment]
> Need to update some of the example cases on https://github.com/dhowe/RiTaJS

how do you mean? these examples should be irrelevant once v2 is released

**Comment by cqx931** [comment]
Aren't we going to keep having example cases for various platforms for rita2?
For example,  this old example case
```
let rs = RiString("The elephant took a bite!");
console.log(rs.features());
```
should be:
```
console.log(RiTa.analyze());
```

**Comment by dhowe** [comment]
ah you mean in the quick-start guides -- yes, they need to be updated

**Comment by cqx931** [comment]
yes, just add a TODO note on that, cause some of the release check items refer to those examples.
